language: node_js

node_js:
  - stable

# branches:
#   only:
#     - master
cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test:coverage

after_success:
  - git config --global user.email "dcodesmith@users.noreply.github.com"
  - git remote rm origin
  - git remote add origin https://dcodesmith:${GH_TOKEN}@github.com/dcodesmith/epg-react-redux-ui.git
  - yarn deploy

after_script:
  - yarn coveralls
