language: node_js

node_js:
  - stable

# branches:
#   only:
#     - master
cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test:coverage
  - yarn build

after_script:
  - yarn coveralls
