export const LOAD_CHANNELS_SUCCESS = 'LOAD_CHANNELS_SUCCESS';
export const UPDATE_CHANNEL_SUCCESS = 'UPDATE_CHANNEL_SUCCESS';
export const CREATE_CHANNEL_SUCCESS = 'CREATE_CHANNEL_SUCCESS';

export const LOAD_PROGRAMMES_SUCCESS = 'LOAD_PROGRAMMES_SUCCESS';
export const CREATE_PROGRAMMES_SUCCESS = 'CREATE_PROGRAMMES_SUCCESS';
export const DELETE_PROGRAMMES_SUCCESS = 'DELETE_PROGRAMMES_SUCCESS';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const SELECT_DATE = 'SELECT_DATE';

export const NEXT_PAGE = 'NEXT_PAGE';
export const PREVIOUS_PAGE = 'PREVIOUS_PAGE';
export const NAVIGATE_PAGE = 'NAVIGATE_PAGE';
